language: go

go:
  - 1.2rc2
  - tip

before_install:
  - sudo add-apt-repository -y ppa:ricotz/testing
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libwebkitgtk-3.0-dev gtk+3.0
  - "export DISPLAY=:99.0"
  - sh -e /etc/init.d/xvfb start

install:
  - go get -tags gtk_3_6 -v ./...

script:
  - go test -tags gtk_3_6 ./...
